# Generated by Django 4.0.4 on 2022-06-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('likes', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('lives_in', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
