# coding: utf-8

# flake8: noqa
"""
    Bioweb REST API

    API for interacting with gene records  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.gene import Gene
from swagger_client.models.gene_ec import GeneEc
from swagger_client.models.gene_list import GeneList
from swagger_client.models.gene_sequencing import GeneSequencing
