# coding: utf-8

"""
    Bioweb REST API

    API for interacting with gene records  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.gene import Gene  # noqa: E501
from swagger_client.rest import ApiException


class TestGene(unittest.TestCase):
    """Gene unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGene(self):
        """Test Gene"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.gene.Gene()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
