# coding: utf-8

"""
    Bioweb REST API

    API for interacting with gene records  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.gene_ec import GeneEc  # noqa: E501
from swagger_client.rest import ApiException


class TestGeneEc(unittest.TestCase):
    """GeneEc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneEc(self):
        """Test GeneEc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.gene_ec.GeneEc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
