# Generated by Django 4.0.4 on 2022-06-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256, unique=True)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256, unique=True)),
                ('sequence', models.CharField(blank=True, max_length=40000, null=True)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.IntegerField()),
                ('clade', models.CharField(max_length=256)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.domain')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(through='organism.ProteinDomainLink', to='organism.domain'),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.taxonomy'),
        ),
        migrations.AddField(
            model_name='domain',
            name='pfam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.pfam'),
        ),
    ]
