# Generated by Django 4.0.4 on 2022-05-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_description', models.CharField(max_length=256)),
                ('start', models.IntegerField(blank=True)),
                ('end', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('family_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256)),
                ('sequence', models.CharField(blank=True, max_length=40000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=256)),
                ('clade', models.CharField(max_length=256)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(blank=True)),
                ('domains', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.domain')),
                ('protein_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.protein')),
                ('taxonomy_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.taxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organism.pfam'),
        ),
    ]
