# Generated by Django 3.0.3 on 2022-05-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3app', '0004_pizza_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
