# Generated by Django 4.0.6 on 2022-08-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=models.ImageField(default='default_picture.png', upload_to='profile_images'),
        ),
    ]
