# Generated by Django 4.0.6 on 2022-08-22 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendbook', '0002_alter_appuser_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='Profile',
        ),
    ]
