# Generated by Django 4.0.6 on 2022-10-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0002_postimage_remove_post_image_postimagelink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postImage',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='postimagelink',
            old_name='postImage',
            new_name='post_image',
        ),
    ]
