# Generated by Django 4.0.6 on 2023-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0003_rename_postimage_post_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.CharField(max_length=100)),
                ('request_to', models.CharField(max_length=100)),
                ('request_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='./friendbook/static/media/post_image'),
        ),
    ]
