# Generated by Django 4.0.6 on 2022-08-23 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0003_rename_appuser_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_image')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
