# Generated by Django 4.0.6 on 2023-02-02 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendbook', '0004_friends_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
