# Generated by Django 4.0.6 on 2023-02-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0008_postlike_remove_post_number_of_likes_postlikelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='friendbook.profile'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='friendbook.profile'),
        ),
    ]
