# Generated by Django 4.0.6 on 2023-02-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0009_alter_postcomment_posted_by_alter_postlike_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikelink',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendbook.postlike'),
        ),
    ]
