# Generated by Django 4.0.6 on 2023-02-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0010_alter_postlikelink_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_user', to='friendbook.profile'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_user', to='friendbook.profile'),
        ),
    ]
