# Generated by Django 4.0.6 on 2023-02-28 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0012_chatmessage_chatmessagelink_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
