# Generated by Django 4.0.4 on 2023-03-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendbook', '0013_chats_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='online_status',
        ),
    ]
